---
name: ci

# yamllint disable-line rule:truthy
on:
  push:
  # https://github.com/orgs/community/discussions/25722#discussioncomment-3248917
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review

concurrency:
  group: ci-${{github.ref}}-${{github.event.pull_request.number || github.run_number}}
  cancel-in-progress: true

jobs:
  prechecks:
    uses: ./.github/workflows/pre-commit.yml
  all-prechecks:
    needs: [prechecks]
    runs-on: ubuntu-latest
    steps:
      - name: Success
        run: "true"
  build-and-test:
    uses: ./.github/workflows/test.yml
